#!/bin/bash

set -e
set -o pipefail

FOLDER_ROOT="$1"
FOLDER_OWNER="$2"
FOLDER_GROUP="$3"

echo "Preparing RAM-based secret location at $FOLDER_ROOT"

mkdir -p "$1"

current_fstype="$(df "$FOLDER_ROOT" --portability -T | tail -n '+2' | awk '{print $2}')"

if [[ "$current_fstype" == "ramfs" ]] ; then
  echo "ramfs already mounted for $FOLDER_ROOT. Skipping mount action."
else
  mount -t ramfs "/dev/fake/ramfs/${FOLDER_OWNER}" "${FOLDER_ROOT}"
fi

chown -R "${FOLDER_OWNER}:${FOLDER_GROUP}" "${FOLDER_ROOT}"
chmod -R o= "${FOLDER_ROOT}"