#!/bin/bash

set -e
set -o pipefail

KMS_SECRET_OUTPUTDIR=$1
KMS_SECRET_USER=$2
KMS_SECRET_GROUP=$3

AWS_REGION="$(curl http://169.254.169.254/latest/dynamic/instance-identity/document --silent --fail | jq .region -rM)"
export AWS_REGION

umask u=rw,go=
chown -R $KMS_SECRET_USER:$KMS_SECRET_GROUP $KMS_SECRET_OUTPUTDIR
chmod u+s,g+s $KMS_SECRET_OUTPUTDIR

for x in $(echo "$KMS_SECRETS_LIST" | tr ',' ' ') ; do

  kms_context="KMS_SECRET_${x}_CONTEXT"
  kms_context="${!kms_context}"
  kms_ciphertext="KMS_SECRET_${x}_CIPHERTEXT"
  kms_ciphertext="${!kms_ciphertext}"
  kms_outputfile="KMS_SECRET_${x}_OUTPUTFILE"
  kms_outputfile="${KMS_SECRET_OUTPUTDIR}/${!kms_outputfile}"

  echo "Decoding secret $x to $kms_outputfile"

  aws kms decrypt --region $AWS_REGION \
    --ciphertext-blob fileb://<(echo "$kms_ciphertext" | base64 --decode) \
    --encryption-context "$kms_context" \
    --query Plaintext --output text \
  | base64 --decode \
  > "$kms_outputfile"

done

chown -R $KMS_SECRET_USER:$KMS_SECRET_GROUP $KMS_SECRET_OUTPUTDIR

echo "All secrets decoded"