#cloud-config
repo_upgrade: security
write_files:
  # Bootstrap
  - path: "/tmp/bootstrap-userdata"
    encoding: b64
    permissions: 0500
    content: "${launch-script}"
runcmd:
  - [ "/tmp/bootstrap-userdata", "${etcd-release-s3-uri}", "${m3-release-s3-uri}", "${m3-query-config-s3-uri}", "${node-exporter-release-s3-uri}", "${node-exporter-installation-files-s3-uri}", "${update-auto-reboot-installation-files-s3-uri}" ]
  - [ "/usr/bin/yum", "update", "--security", "--assumeyes" ] # Not all seem to get applied automatically