#!/bin/bash

set -e
set -o pipefail

umask u=rw,go=
chown -R prometheus:prometheus /var/run/prometheus/secrets
chmod u+s,g+s /var/run/prometheus

for x in $(echo "$PROMETHEUS_SECRETS_LIST" | tr ',' ' ') ; do

  kms_context="PROMETHEUS_SECRET_${x}_CONTEXT"
  kms_context="${!kms_context}"
  kms_ciphertext="PROMETHEUS_SECRET_${x}_CIPHERTEXT"
  kms_ciphertext="${!kms_ciphertext}"
  kms_outputfile="PROMETHEUS_SECRET_${x}_OUTPUTFILE"
  kms_outputfile="/var/run/prometheus/secrets/${!kms_outputfile}"

  echo "Decoding secret $x to $kms_outputfile"

  aws kms decrypt --region us-east-1 \
    --ciphertext-blob fileb://<(echo "$kms_ciphertext" | base64 --decode) \
    --encryption-context "$kms_context" \
    --query Plaintext --output text \
  | base64 --decode \
  | base64 --decode \
  > "$kms_outputfile"

done

chown -R prometheus:prometheus /var/run/prometheus/secrets

echo "All secrets decoded"