# WARNING:
# M3 mainenance: it is only safe for one node out of a 3-replica set to be offline at any time
# Changes to this file can cause a Terraform state change affecting the instance

db:
  logging:
    level: info

  metrics:
    prometheus:
      handlerPath: /metrics
    sanitization: prometheus
    samplingRate: 1.0
    extended: detailed

  hostID:
    resolver: hostname

  config:
   service:
     env: default_env
     zone: embedded
     service: m3db
     cacheDir: /var/lib/m3kv
     etcdClusters:
       - zone: embedded
         endpoints:
           - ${etcd-hostip0}:2379
           - ${etcd-hostip1}:2379
           - ${etcd-hostip2}:2379

  listenAddress: 0.0.0.0:9000
  clusterListenAddress: 0.0.0.0:9001
  httpNodeListenAddress: 0.0.0.0:9002
  httpClusterListenAddress: 0.0.0.0:9003
  debugListenAddress: 0.0.0.0:9004

  client:
    writeConsistencyLevel: majority
    readConsistencyLevel: unstrict_majority

  gcPercentage: 100

  writeNewSeriesAsync: true
  writeNewSeriesLimitPerSecond: 1048576
  writeNewSeriesBackoffDuration: 2ms

  bootstrap:
    bootstrappers:
        - filesystem
        - commitlog
        - peers
        - uninitialized_topology
    commitlog:
      returnUnfulfilledForCorruptCommitLogFiles: true

  cache:
    series:
      policy: lru
    postingsList:
      size: 262144

  commitlog:
    flushMaxBytes: 5242880
    flushEvery: 5s
    queue:
      calculationType: fixed
      size: 1048576

  fs:
    filePathPrefix: /var/lib/m3-data/data
    throughputLimitMbps: 200.0

 # Configuration for various different object pools that M3DB uses.
  pooling:
    blockAllocSize: 16
    type: simple
    seriesPool:
        size: 64000
        lowWatermark: 0.7
        highWatermark: 1.0
    blockPool:
        size: 64000
        lowWatermark: 0.7
        highWatermark: 1.0
    encoderPool:
        size: 130000
        lowWatermark: 0.7
        highWatermark: 1.0
    closersPool:
        size: 52000
        lowWatermark: 0.7
        highWatermark: 1.0
    contextPool:
        size: 65536
        lowWatermark: 0.7
        highWatermark: 1.0
    segmentReaderPool:
        size: 4096
        lowWatermark: 0.7
        highWatermark: 1.0
    iteratorPool:
        size: 512
        lowWatermark: 0.7
        highWatermark: 1.0
    fetchBlockMetadataResultsPool:
        size: 16384
        capacity: 32
        lowWatermark: 0.7
        highWatermark: 1.0
    fetchBlocksMetadataResultsPool:
        size: 32
        capacity: 4096
        lowWatermark: 0.7
        highWatermark: 1.0
    blockMetadataPool:
        size: 16384
        lowWatermark: 0.7
        highWatermark: 1.0
    blockMetadataSlicePool:
        size: 16384
        capacity: 32
        lowWatermark: 0.7
        highWatermark: 1.0
    blocksMetadataPool:
        size: 16384
        lowWatermark: 0.7
        highWatermark: 1.0
    blocksMetadataSlicePool:
        size: 32
        capacity: 4096
        lowWatermark: 0.7
        highWatermark: 1.0
    identifierPool:
        size: 262144
        lowWatermark: 0.7
        highWatermark: 1.0
    bytesPool:
        buckets:
            - capacity: 16
              size: 131072
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 32
              size: 65536
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 64
              size: 32768
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 128
              size: 16384
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 256
              size: 16384
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 1440
              size: 4096
              lowWatermark: 0.7
              highWatermark: 1.0
            - capacity: 1024
              size: 8192
              lowWatermark: 0.7
              highWatermark: 1.0